package com.envimate.messageMate.shared.context;

public enum TestExecutionProperty {
    SINGLE_SEND_MESSAGE,
    EXPECTED_RECEIVERS,
    INITIAL_SUBSCRIBER,
    EXPECTED_SUBSCRIBER,
    POTENTIAL_RECEIVERS,
    SINGLE_RECEIVER,
    SUT,
    MESSAGE_BUS,
    CHANNEL,
    MESSAGES_SEND,
    MESSAGES_SEND_OF_INTEREST,
    EXPECTED_CHANGED_CONTENT,
    EXECUTION_END_SEMAPHORE,
    RESULT,
    EXECUTE_MESSAGE_BUS_IN_OWN_THREAD,
    ERROR_SUBSCRIBER,
    EXPECTED_FILTER,
    EXCEPTION,
}
