package com.envimate.messageMate.useCaseAdapter.singleObjectParameterButDifferentToEvent;


import com.envimate.messageMate.useCaseAdapter.UseCaseAdapterSpecs;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(SingleObjectParameterButDifferentToEventConfigurationResolver.class)
public class SingleObjectParameterButDifferentToEventUseCaseAdapterSpecs implements UseCaseAdapterSpecs {

}
